---
# file: roles/docker-mediawiki/tasks/main.yaml

- name: Check preconditions
  assert:
    that:
    - wiki_db_root_password is defined
    - wiki_db_password is defined

- name: docker_container.conf dir
  file:
    state: directory
    path: '{{ docker_restore_config_base_dir }}/{{ wiki_dv_name }}'
    owner: root
    group: root
    mode: 'u=rwx,g=rx,o=rx'
    recurse: no

# *****************************************************************************
# backup script part

- name: Assemble dir for backup scripts
  file:
    path: /usr/libexec/bacula/backup-scripts
    state: directory

- name: before_backup script part
  template:
    src: before_backup.j2
    dest: /usr/libexec/bacula/backup-scripts/55.before_backup.wiki

- name: after_backup script part
  template:
    src: after_backup.j2
    dest: /usr/libexec/bacula/backup-scripts/55.after_backup.wiki

# *****************************************************************************
# update the Docker restore config

- name: make config.sh
  template:
    src: config.sh.j2
    dest: '{{ docker_restore_config_base_dir }}/{{ wiki_dv_name }}/config.sh'
    backup: yes
    owner: root
    group: tape
    mode: 'u=rw,g=r,o='

- name: exists - state file
  stat:
    path: '{{ docker_restore_config_base_dir }}/{{ wiki_dv_name }}/restore.date.txt'
    get_checksum: False
    get_md5: False
  register: st_mediawiki_restore

# *****************************************************************************
# Update or make the image.

- name: Checkout image repo
  git:
    repo: '{{ wiki_image_repo }}'
    version: master
    dest: '{{ docker_projects_dir }}/docker-mediawiki'

- name: copy script
  copy:
    remote_src: true
    src: '{{ docker_projects_dir }}/docker-mediawiki/mediawiki.sh'
    dest: '{{ docker_restore_config_base_dir }}/{{ wiki_dv_name }}/'
    mode: 'u=rwx,g=rx,o=rx'

- name: build image
  docker_build:
    image_name: '{{ wiki_image_name }}'
    image_tag: '{{ docker_image_tag }}'
    dockerfile_dir: '{{ docker_projects_dir }}/docker-mediawiki'

# *****************************************************************************
# Create the data volumes

- name: data-volume container (mediwiki)
  docker_datavolume:
    image_name: '{{ wiki_image_name }}'
    image_tag: '{{ docker_image_tag }}'
    data_volume_container_name: '{{ wiki_dv_name }}'

- name: data-volume container (mysql)
  docker_datavolume:
    image_name: '{{ wiki_db_image_name }}'
    image_tag: '{{ docker_image_tag }}'
    data_volume_container_name: '{{ wiki_db_dv_name }}'

- name: stop prev container (mysql)
  docker_container:
    image: '{{ wiki_db_image_name }}'
    name: '{{ wiki_db_container_name }}'
    state: stopped

- name: initial populate (mysql)
  docker_db_init:
    image_name: '{{ wiki_db_image_name }}'
    image_tag: '{{ docker_image_tag }}'
    container_name: '{{ wiki_db_dv_name }}_init_db'
    data_volume_container_name: '{{ wiki_db_dv_name }}'
    database_name: wikidb
    database_user: '{{ wiki_db_user }}'
    database_password: '{{ wiki_db_password | quote }}'
    database_root_password: '{{ wiki_db_root_password | quote }}'

# *****************************************************************************
# Start the data container running

- name: start container (mysql)
  docker_container:
    detach: true
    image: '{{ wiki_db_image_name }}:{{ docker_image_tag }}'
    name: '{{ wiki_db_container_name }}'
    restart_policy: '{{ docker_restart_policy }}'
    volumes_from: '{{ wiki_db_dv_name }}'

- name: start container (mediwiki)
  docker_container:
    detach: true
    env:
      WIKI_HOSTNAME: '{{ container_addr_map.wiki.hostname }}'
      WIKI_MAIL_USER: 'wiki'
      WIKI_MAIL_PASSWORD: '{{ wiki_email_password | quote }}'
    hostname: '{{ container_addr_map.wiki.hostname }}'
    image: '{{ wiki_image_name }}:{{ docker_image_tag }}'
    link:
      - '{{ openldap_container_name }}:wiki_ldap'
      - '{{ wiki_db_container_name }}:wiki_db'
      - '{{ exim4_container_name }}:{{ container_addr_map.exim4.hostname }}'
    name: '{{ wiki_container_name }}'
    ports: '{{ container_port_map.wiki.port_args }}'
    restart_policy: '{{ docker_restart_policy }}'
    state: started
    volumes_from:
      - '{{ openssl_dv_name }}'
      - '{{ wiki_dv_name }}'

# *****************************************************************************
# restore?

- include_tasks: restore.yml
  when: st_mediawiki_restore.stat.exists == False
